### PR TITLE
configurable controls

### PR DESCRIPTION
**Pull request by Oli4242**
Hey! I've worked on making the controls more configurable. It works as expected here https://github.com/luizbills/phaser-behaviors/pull/1#issuecomment-269902277 (both multiple and single controls works)

### CODE REVIEW

**Comment by luizbills** [comment]
Thank you.
It looks well done. But I'm running out of time to test it for now. As soon as possible I will review it.

**Comment by luizbills** [comment]
Sorry for the delay. I have tested your purpose and my console pointed some errors.

1. you are using `this._addKeys` inside of a behavior. But the behavior not has a context (`this`), use `.process` or put your helpers inside of `options`
Examples:
```js
// inside of options LINE 24
...
    left: options._addKeys(object.game, controls.left),
    right: options._addKeys(object.game, controls.right),
...
```
or
```js
// with .process LINE 24
...
    left: object.behaviors.process( options.$key, '_addKeys', object.game, controls.left ),
...
```

> note: `.process` is called internally to fire the main loop events but it's a public method and can return values.

I personally prefer the solution using `options`. It would be nice to override the `isDown` method using the options, if necessary.

**Comment by Oli4242** [comment]
I understand for the delay, np :)

It works fine on my computer, I'm using it in a project and I've also tested with your platformer demo. How do you get those errors?

(I'd also prefer the solution using `options` but I find it a bit strange to have that kind of private methods into `options`)

**Comment by luizbills** [comment]
Hi @Oli4242,

I put your modified behavior version in this https://phaser-platformer-behavior.surge.sh. Open the console to you see the errors that I mentioned.

**Comment by Oli4242** [comment]
oops! you're right... I guess it's because I'm still using an outdated version of the plugin in my current project.

**Comment by Oli4242** [comment]
I actually like the idea that `options` only contains the configuration and the `behavior` contains all the logic.

So I suggest 2 more options:

1. Update the Behavior System so it runs methods within the behavior's context
2. I could move `_addKeys` and `_isDown` outside the behavior like this:
```js
var Platformer = (function() {
  function isDown() { ... }
  function addKeys() { ... }
  var PlatformerBheavior = { ... }
  return PlatformerBehavior
})()
```
(the closure avoids namespace pollution since `isDown` and `addKeys` aren't needed outside)

**Comment by luizbills** [comment]
I had the same idea as you hahaha to move those functions to outside of behavior and create a closure.

About `behavior's context`, I like to avoid using `this`. For that reason I pass the parent object and options as arguments.

**Comment by luizbills** [comment]
@Oli4242 Can you already put the code in the [template](https://github.com/luizbills/phaser-behaviors/blob/master/behavior-template.js)? This template has UMD support and its own closure.

**Comment by Oli4242** [comment]
Is it ok?

**Comment by luizbills** [comment]
Works. Thank you

**Pull request merged**
