### PR TITLE
[Behavior] Platformer

### PR DESCRIPTION
**Pull request by luizbills**
- [x] Implement more controls.
- [ ] Add docs.

### CODE REVIEW

**Comment by luizbills** [comment]
@Oli4242 can you help test this and other behaviors?

**Comment by luizbills** [comment]
A game to test using this behavior: https://github.com/luizbills/phaser-platform-game

**Comment by Oli4242** [comment]
It looks fine to me but 3 things:

1. I remember having some troubles with Tilemaps and `body.touching` (or maybe `body.blocked`), have you tested?

2. I would handle controls with something like: `controls: { left: ..., right: ..., jump: ..., left2: ..., right2: ..., jump2: ... }` that would allow both space and up to jump or any "exotic" controls like `ZQWASD` to handle both `WASD` and `ZQSD` (for AZERTY keyboards) or `IJKL` for player 2, etc.

3. I'm curious about the reason why you define your own `NULL` instead of using javascript's `null` / `undefined` ?

**Comment by luizbills** [comment]
@Oli4242 

1. I've tested using this demo https://github.com/luizbills/phaser-platform-game . You know a better method?

2. I think in something like this:
```js
// single control
player.behaviors.set('moviment', Platformer, {
    controls: {
        left: Phaser.KeyCode.LEFT,
        right: Phaser.KeyCode.RIGHT,
        jump: Phaser.KeyCode.UP,
    }
})

// or multiple controls
player.behaviors.set('moviment', Platformer, {
    controls: {
        left: [Phaser.KeyCode.LEFT, Phaser.KeyCode.A],
        right: [Phaser.KeyCode.RIGHT, Phaser.KeyCode.D]
        jump: [Phaser.KeyCode.UP, Phaser.KeyCode.SPACE, Phaser.KeyCode.W]
    }
})
```

3. It's just a personal choice. `undefined` (my `NULL`) is more safe for me (because I always use `===`) and `null` returns `"object"` with `typeof` (but I not use typeof).

**Pull request merged**
